apiVersion: apps/v1
kind: Deployment
metadata:
  name: task-manager-backend
  labels:
    app: task-manager-backend

spec:
  replicas: {{ .Values.backend.replicaCount }}

  selector:
    matchLabels:
      app: task-manager-backend

  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0

  template:
    metadata:
      labels:
        app: task-manager-backend

    spec:
      imagePullSecrets:
        {{- toYaml .Values.imagePullSecrets | nindent 8 }}

      containers:
        - name: backend
          image: "{{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag }}"
          imagePullPolicy: {{ .Values.backend.image.pullPolicy }}

          ports:
            - name: http
              containerPort: {{ .Values.backend.service.port }}

          env:
            - name: DB_HOST
              value: task-manager-postgres

            - name: DB_PORT
              value: "5432"

            - name: DB_NAME
              value: taskdb

            - name: DB_USERNAME
              value: postgres

            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: task-manager-postgres-secret
                  key: POSTGRES_PASSWORD

          readinessProbe:
            httpGet:
              path: /api/health
              port: http
            initialDelaySeconds: 20
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 3

          livenessProbe:
            httpGet:
              path: /api/health
              port: http
            initialDelaySeconds: 30
            periodSeconds: 15
            timeoutSeconds: 3
            failureThreshold: 3

          resources:
{{ toYaml .Values.backend.resources | indent 12 }}