apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: task-manager-postgres-pvc
  labels:
    app: task-manager-postgres

spec:
  accessModes:
    - ReadWriteOnce

  resources:
    requests:
      storage: {{ .Values.postgres.storage.size }}
